### PR TITLE
fix: enable support for TS param props

### LINKED ISSUE #65: Support for parameter properties (shorthand constructor)
At the moment this plugin doesn't seem to support parameter properties ([explained here](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties)).

Imagine the following code:

```js
export default class BaseFragment extends ManagedObject {

    view: View;

    constructor(public controller: BaseController) {
        super();
        this.view = controller.getView();
    }
}
```

This should automatically generate a public property `controller` and assign the value which was passed to the constructor.

This works for regular classes but as soon as I inherit from UI5 classes (and the code will be transpiled to `sap.ui.define(...)`) I receive the error `Property params[0] of FunctionExpression expected node to be of a type ["Identifier","Pattern","RestElement"] but instead got "TSParameterProperty"`.

### PR DESCRIPTION
**Pull request by petermuessig**
Fixes #65

### CODE REVIEW

File: packages/plugin/src/classes/helpers/classes.js [hunk 1]
```diff
@@ -69,13 +69,50 @@ export function convertClassToUI5Extend(
...
     if (t.isClassMethod(member)) {
+      const isConstructor = member.kind === "constructor";
+      const membersToAssign = [];
+      const params = isConstructor
+        ? member.params?.map((param) => {
+            // handling of parameter properties for constructors (TypeScript):
+            // https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties
+            //   -> extracting the real parameters and store the members to assign
+            if (param.type === "TSParameterProperty") {
+              membersToAssign.push(param.parameter);
```
Comment (akudev) [inline packages/plugin/src/classes/helpers/classes.js:80]: Does this discard all information about the parameter property except the parameter itself? As far as I see, a TSParameterProperty also has: accessibility ("public" | "private" | "protected"), decorators, override, readonly

I'd still love to see this merged as-is, but (as witnessed by the underlying issue report) in the long run the expectation will be that every language construct of TypeScript related to class definition will be properly transformed. We'll have to check this in a systematic way - or be faster with allowing ES6 classes in UI5 apps.

**Review by akudev — APPROVED** [review]

File: packages/plugin/src/classes/helpers/classes.js (hunk 1 above)
Comment (petermuessig) [reply packages/plugin/src/classes/helpers/classes.js:80]: The other PR #100 changes the way the plugin is executed. It then runs in the Class visitor exit phase and therefore, the TypeScript plugin might have been run already. IMO, it is not the plugin which should take care about this, furthermore it should be the TypeScript plugin upfront.
